[tool]
[tool.poetry]
name = "WylineUserBot_Deployer"
version = "1.0"
description = "Automatic Deploy WylineUserBot to Heroku"
authors = ["Patron"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
